/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_BIwindowG (void);
GtkWidget* create_JDwindowG (void);
GtkWidget* create_BIdialog (void);
GtkWidget* create_JDdialog (void);
GtkWidget* create_RAwindowG (void);
GtkWidget* create_RAdialog (void);
GtkWidget* create_TRwindowG (void);
GtkWidget* create_TRdialog (void);
GtkWidget* create_BHwindowG (void);
GtkWidget* create_BHdialog (void);
GtkWidget* create_LoginWindow (void);
GtkWidget* create_AdminWindow (void);
GtkWidget* create_ElecWindow (void);
GtkWidget* create_VoteWindow (void);
GtkWidget* create_Statwindow (void);
GtkWidget* create_gestionw (void);
GtkWidget* create_statw (void);
GtkWidget* create_dialog1 (void);
