name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential cmake

    - name: Build and install
      run: |
        cd Interface
        cmake .
        make
        sudo make install
